"""add rendered_prompt to drafts

Revision ID: 82c08cff870f
Revises: 9936c4eeb5cb
Create Date: 2026-07-05 11:25:24.294324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c08cff870f'
down_revision: Union[str, None] = '9936c4eeb5cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drafts', sa.Column('rendered_prompt', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drafts', 'rendered_prompt')
    # ### end Alembic commands ###
